import type { Profile } from "../profile";
import { C } from "./theme";
import { renderSkillGroups } from "./skills";
import pkg from "../../package.json" with { type: "json" };

function devEnvRows(lines: string[]): string {
  return lines
    .map((d) => {
      const sep = d.indexOf(" | ");
      if (sep === -1) return `<div class="devenv-row"><span class="devenv-val">${d}</span></div>`;
      return `<div class="devenv-row"><span class="devenv-key">${d.slice(0, sep)}</span><span class="devenv-val">${d.slice(sep + 3)}</span></div>`;
    })
    .join("");
}

export function buildHtml(p: Profile, photoUrl: string | null): string {
  const attr = p.attribution;
  const r = p.recent_role;
  const prevExp = p.previous_experience;

  const footerHtml = attr?.enabled
    ? `<footer class="cv-footer">
        <span class="footer-icon">⚙</span>
        GENERATED BY JOBBOT v${pkg.version}
        <span class="footer-sep">◆</span>
        <a href="${attr.repo}" class="footer-link">${attr.repo}</a>
      </footer>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@600;700;900&family=Rajdhani:wght@500;600;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
<style>
@page { margin: 0; size: A4; }
* { margin: 0; padding: 0; box-sizing: border-box; }
html, body { width: 210mm; height: 297mm; }

body {
  background: ${C.base};
  color: ${C.text};
  font-family: 'Inter', system-ui, sans-serif;
  font-size: 11px;
  line-height: 1.5;
  display: flex;
  flex-direction: column;
}

body::before {
  content: '';

  position: fixed;
  inset: 0;

  background-image:
    repeating-linear-gradient(
      0deg,
      rgba(255,255,255,0.015),
      rgba(255,255,255,0.015) 1px,
      transparent 1px,
      transparent 3px
    );


  pointer-events: none;

  opacity: 0.25;

  z-index: 9999;
}

/* ── HERO HEADER ── */
header {
  position: relative;
  min-height: 300px;
  background-color: rgba(24, 24, 37, 0.25);
  backdrop-filter: blur(4px);
  -webkit-backdrop-filter: blur(4px);
  overflow: hidden;
  border-bottom: 2px solid ${C.blue};
  flex-shrink: 0;
  z-index: 0;
  display: flex;
  align-items: stretch;
  padding: 20px;
}
header::after {
  content: '';
  position: absolute;
  bottom: 12px; right: 14px;
  width: 14px; height: 14px;
  border-bottom: 2px solid ${C.blue};
  border-right: 2px solid ${C.blue};
  z-index: 5;
  pointer-events: none;
}
.hero-glow {
  position: absolute;
  top: -30px; left: -10px;
  width: 240px; height: 200px;
  background: radial-gradient(ellipse, ${C.blue}22 0%, transparent 50%);
  pointer-events: none;
}
.header-content {
  position: relative;
  z-index: 4;
  padding: 24px;
  max-width: 65%;
  background: rgba(24, 24, 37, 0.75);

  backdrop-filter: blur(8px);
  -webkit-backdrop-filter: blur(8px);

  border: 1px solid rgba(255,255,255,0.04);

  box-shadow:
    0 10px 24px rgba(0,0,0,0.25);

  border-radius: 8px;

  display: flex;
  flex-direction: column;
  justify-content: center;
}
.header-content::before {
  content: '';
  position: absolute;
  top: 12px; left: 14px;
  width: 14px; height: 14px;
  border-top: 2px solid ${C.blue};
  border-left: 2px solid ${C.blue};
}
h1 {
  font-family: 'Cinzel', serif;
  font-size: 23px;
  font-weight: 900;
  line-height: 1.1;
  letter-spacing: 1.4px;
  color: ${C.text};
  text-shadow: 0 0 24px ${C.blue}66, 0 0 48px ${C.blue}33;
}
h1 em {
  color: ${C.blue};
  font-style: normal;
  text-shadow: 0 0 20px ${C.blue}88;
}
.role-badge {
  display: flex;
  align-items: center;
  justify-content: center;

  margin: 4px 0;
  padding: 10px;

  background: ${C.blue};
  color: ${C.crust};

  font-family: 'Rajdhani', sans-serif;
  font-size: 10px;
  font-weight: 900;

  letter-spacing: 2px;
  text-transform: uppercase;

  clip-path: polygon(
    10px 0,
    calc(100% - 10px) 0,
    100% 50%,
    calc(100% - 10px) 100%,
    10px 100%,
    0 50%
  );

  box-shadow: 0 6px 18px rgba(0,0,0,0.25);
}
.contacts {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  font-size: 8.8px;
  color: ${C.subtext0};
}
.contacts span { display: flex; align-items: center; gap: 4px; }
.contacts .ic { color: ${C.sapphire}; }
.summary-text {
  margin-top: 10px;
  max-width: 460px;
  padding-left: 10px;
  border-left: 2px solid ${C.surface2};
  color: ${C.subtext0};
  font-size: 9.2px;
  line-height: 1.55;
}

/* ── LAYOUT ── */
.content-area {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
.body {
  flex: 1;
  display: grid;
  grid-template-columns: 1fr 37%;
  min-height: 0;
}
.main {
  padding: 16px 18px 16px 20px;
  background: ${C.base};
  border-right: 1px solid ${C.surface0};
  overflow: hidden;
}

.side {
  padding: 16px;

  background: rgba(17, 17, 27, 0.82);

  backdrop-filter: blur(14px);
  -webkit-backdrop-filter: blur(14px);

  border-left: 1px solid rgba(255,255,255,0.04);
  border-top: 2px solid ${C.teal};

  box-shadow:
    inset 0 1px 0 rgba(255,255,255,0.03);
}

/* ── SECTION HEADERS ── */
section { margin-bottom: 14px; }
h2 {
  display: flex;
  align-items: center;
  gap: 7px;
  margin-bottom: 9px;
  padding-bottom: 4px;
  border-bottom: 1px solid ${C.surface0};
  font-family: 'Rajdhani', sans-serif;
  font-size: 9.5px;
  font-weight: 700;
  letter-spacing: 3px;
  text-transform: uppercase;
  color: ${C.blue};
}
h2 .h2-diamond {
  width: 6px; height: 6px;
  background: currentColor;
  transform: rotate(45deg);
  flex-shrink: 0;
}
h2.mauve    { color: ${C.mauve};    }
h2.teal     { color: ${C.teal};     }
h2.lavender { color: ${C.lavender}; }
h2.green    { color: ${C.green};    }

/* ── EXPERIENCE ── */
.exp-card {
  background: ${C.surface0};
  border: 1px solid ${C.surface1};
  border-left: 3px solid ${C.blue};

  clip-path: polygon(
    0 0,
    calc(100% - 10px) 0,
    100% 10px,
    100% 100%,
    0 100%
  );

  box-shadow: inset 3px 0 12px ${C.blue}33;

  padding: 10px 14px;
  margin-bottom: 10px;
}
.exp-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 2px;
}
.exp-title {
  font-family: 'Rajdhani', sans-serif;
  font-size: 12px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  color: ${C.text};
  text-shadow: 0 0 12px ${C.blue}66;
}
.exp-period {
  font-family: 'Rajdhani', sans-serif;
  font-size: 8.5px;
  font-weight: 600;
  color: ${C.mauve};
  background: ${C.surface1};
  border-left: 2px solid ${C.mauve};
  padding: 2px 8px 2px 7px;
  white-space: nowrap;
  letter-spacing: 0.5px;
}
.exp-company {
  margin-bottom: 2px;
  color: ${C.sapphire};
  font-size: 9px;
  font-weight: 600;
}
.exp-reason {
  margin-bottom: 7px;
  color: ${C.overlay1};
  font-size: 8.2px;
  font-style: italic;
}
.exp-card ul { padding-left: 14px; }
.exp-card li {
  margin-bottom: 3px;
  color: ${C.subtext1};
  font-size: 9px;
  line-height: 1.45;
}
.exp-card li::marker { color: ${C.teal}; }
.prev-timeline {
  position: relative;
  padding-left: 18px;
  margin-bottom: 6px;
}
.prev-timeline::before {
  content: '';
  position: absolute;
  left: 3px;
  top: 0;
  bottom: 0;
  width: 2px;
  background: ${C.surface1};
}
.prev-entry {
  position: relative;
  margin-bottom: 5px;
  padding: 3px 0;
  color: ${C.subtext0};
  font-size: 8.8px;
  line-height: 1.45;
}
.prev-entry::before {
  content: '';
  position: absolute;
  left: -19px;
  top: 8px;
  width: 8px;
  height: 8px;
  background: ${C.teal};
  border-radius: 50%;
  box-shadow: 0 0 6px ${C.teal}aa;
}
.edu-entry {
  margin-bottom: 6px;
  padding: 6px 9px;
  background: ${C.surface0};
  border-left: 2px solid ${C.lavender};
  color: ${C.subtext1};
  font-size: 8.5px;
  line-height: 1.4;
}

/* ── BOTTOM STRIP ── */
.strip {
  flex-shrink: 0;
  display: flex;
  background: rgba(17, 17, 27, 0.88);
  backdrop-filter: blur(14px);
  -webkit-backdrop-filter: blur(14px);
  border-top: 2px solid ${C.surface0};
  box-shadow: 0 -4px 20px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.04);
}
.strip-col {
  flex: 1;
  padding: 10px 13px;
  border-right: 1px solid ${C.surface0};
  overflow: hidden;
}
.strip-col:last-child { border-right: none; }
.strip-h {
  font-family: 'Rajdhani', sans-serif;
  font-size: 7.5px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 2.5px;
  margin-bottom: 6px;
  padding-bottom: 3px;
  display: flex;
  align-items: center;
  gap: 5px;
  border-bottom: 1px solid ${C.surface0};
}
.sh-d {
  display: inline-block;
  width: 4px; height: 4px;
  background: currentColor;
  transform: rotate(45deg);
  flex-shrink: 0;
}
.devenv-row {
  display: flex;
  align-items: baseline;
  gap: 8px;
  margin-bottom: 3px;
}
.devenv-key {
  font-family: 'Rajdhani', sans-serif;
  font-size: 8px;
  font-weight: 700;
  color: ${C.green};
  letter-spacing: 0.8px;
  text-transform: uppercase;
  min-width: 50px;
  flex-shrink: 0;
}
.devenv-val {
  font-size: 8.5px;
  color: ${C.subtext1};
  line-height: 1.35;
}
.strip-lang {
  font-size: 8.5px;
  color: ${C.subtext1};
  padding: 3px 0;
  border-bottom: 1px solid ${C.surface0};
}
.strip-lang:last-child { border-bottom: none; }
.strip-hobby {
  font-size: 8px;
  color: ${C.subtext0};
  padding: 2px 0 2px 7px;
  border-left: 2px solid ${C.peach};
  margin-bottom: 3px;
  line-height: 1.35;
}

/* ── FOOTER ── */
.cv-footer {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 7px 24px;
  background: ${C.crust};
  border-top: 1px solid ${C.surface0};
  font-family: 'Rajdhani', sans-serif;
  font-size: 9px;
  font-weight: 600;
  letter-spacing: 1px;
  color: ${C.subtext0};
  flex-shrink: 0;
}
.footer-icon { color: ${C.blue}; }
.footer-sep  { color: ${C.surface2}; font-size: 7px; }
.footer-link { color: ${C.blue}; text-decoration: none; letter-spacing: 0; font-weight: 500; }
</style>
</head>
<body${photoUrl ? ` style="background-image: linear-gradient(to right, ${C.base} 0%, ${C.base}cc 35%, ${C.base}77 55%, ${C.base}22 76%, transparent 80%), linear-gradient(to top, ${C.base} 0%, ${C.base}ee 6%, ${C.base}55 15%, transparent 82%), url('${photoUrl}'); background-position: 0 0, 0 100%, top -50px right -125px; background-size: 100% 100%, 100% 100%, 75% auto; background-repeat: no-repeat, no-repeat, no-repeat;"` : ""}>
<header>
  <div class="hero-glow"></div>
  <div class="header-content">
    <h1>${p.personal.name.split(" ").slice(0, -1).join(" ")} <em>${p.personal.name.split(" ").slice(-1)[0]}</em></h1>
    <div class="role-badge">GENERALIST · IT SPECIALIST · DEVELOPER · GAME INDUSTRY</div>
    <div class="contacts">
      <span><span class="ic">✉</span>${p.personal.email}</span>
      <span><span class="ic">☏</span>${p.personal.phone}</span>
      <span><span class="ic">◈</span>${p.personal.location}</span>
      ${p.personal.github ? `<span><span class="ic">⌘</span>${p.personal.github}</span>` : ""}
      ${p.personal.website ? `<span><span class="ic">⌂</span>${p.personal.website}</span>` : ""}
    </div>
    ${p.personal.summary ? `<div class="summary-text">${p.personal.summary}</div>` : ""}
  </div>
</header>

<div class="content-area">
<div class="body">

  <div class="main">
    <section>
      <h2><span class="h2-diamond"></span>Experience</h2>
      <div class="exp-card">
        <div class="exp-header">
          <span class="exp-title">${r.title}</span>
          <span class="exp-period">${r.period}</span>
        </div>
        <div class="exp-company">${r.company}</div>
        <div class="exp-reason">${r.end_reason}</div>
        <ul>${r.duties.map((d) => `<li>${d}</li>`).join("")}</ul>
      </div>
      <div class="prev-timeline">
        ${prevExp.map((e) => `<div class="prev-entry">${e.entry}</div>`).join("")}
      </div>
    </section>

    <section>
      <h2 class="lavender"><span class="h2-diamond"></span>Education</h2>
      ${p.education.map((e) => `<div class="edu-entry">${e.entry}</div>`).join("")}
    </section>
  </div>

  <div class="side">
    <section>
      <h2 class="teal"><span class="h2-diamond"></span>Skills</h2>
      ${renderSkillGroups(p.skills)}
    </section>
  </div>

</div>

<div class="strip">
  ${
    p.dev_environment?.length
      ? `<div class="strip-col">
    <div class="strip-h" style="color:${C.green}"><span class="sh-d"></span>&gt;_ Dev Environment</div>
    ${devEnvRows(p.dev_environment)}
  </div>`
      : ""
  }

  ${
    p.hobbies?.length
      ? `<div class="strip-col">
    <div class="strip-h" style="color:${C.peach}"><span class="sh-d"></span>Interests</div>
    ${p.hobbies.map((h) => `<div class="strip-hobby">${h}</div>`).join("")}
  </div>`
      : ""
  }

  <div class="strip-col">
    <div class="strip-h" style="color:${C.mauve}"><span class="sh-d"></span>Languages</div>
    ${p.languages.list.map((l) => `<div class="strip-lang">${l}</div>`).join("")}
  </div>
</div>
</div>

${footerHtml}
</body>
</html>`;
}
