import type { Profile } from "../profile";
import { C } from "./theme";
import pkg from "../../package.json" with { type: "json" };

export function buildLetterHtml(
  p: Profile,
  jobTitle: string,
  company: string,
  letterBody: string,
  date: string,
): string {
  const attr = p.attribution;

  const footerHtml = attr?.enabled
    ? `<footer class="ltr-footer">
        <span class="footer-icon">⚙</span>
        GENERATED BY JOBBOT v${pkg.version}
        <span class="footer-sep">◆</span>
        <a href="${attr.repo}" class="footer-link">${attr.repo}</a>
      </footer>`
    : "";

  const bodyLines = letterBody
    .split("\n")
    .map((line) => (line.trim() === "" ? `<div class="para-gap"></div>` : `<p>${line}</p>`))
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@600;700;900&family=Rajdhani:wght@500;600;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
<style>
@page { margin: 0; size: A4; }
* { margin: 0; padding: 0; box-sizing: border-box; }
html, body { width: 210mm; height: 297mm; }

body {
  background: ${C.base};
  color: ${C.text};
  font-family: 'Inter', system-ui, sans-serif;
  font-size: 10.5px;
  line-height: 1.6;
  display: flex;
  flex-direction: column;
}

/* ── HEADER ── */
header {
  flex-shrink: 0;
  padding: 22px 32px 18px;
  background: ${C.crust};
  border-bottom: 2px solid ${C.blue};
  position: relative;
  overflow: hidden;
}
header::before {
  content: '';
  position: absolute;
  top: -40px; left: -20px;
  width: 260px; height: 200px;
  background: radial-gradient(ellipse, ${C.blue}18 0%, transparent 70%);
  pointer-events: none;
}
header::after {
  content: '';
  position: absolute;
  bottom: 10px; right: 12px;
  width: 12px; height: 12px;
  border-bottom: 2px solid ${C.blue};
  border-right: 2px solid ${C.blue};
}
.ltr-bracket {
  position: absolute;
  top: 10px; left: 12px;
  width: 12px; height: 12px;
  border-top: 2px solid ${C.blue};
  border-left: 2px solid ${C.blue};
}
.ltr-name {
  font-family: 'Cinzel', serif;
  font-size: 20px;
  font-weight: 900;
  letter-spacing: 1.2px;
  color: ${C.text};
  text-shadow: 0 0 20px ${C.blue}55, 0 0 40px ${C.blue}22;
  line-height: 1.1;
}
.ltr-name em {
  color: ${C.blue};
  font-style: normal;
  text-shadow: 0 0 16px ${C.blue}77;
}
.ltr-contacts {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-top: 7px;
  font-size: 8.5px;
  color: ${C.subtext0};
}
.ltr-contacts span { display: flex; align-items: center; gap: 4px; }
.ltr-contacts .ic { color: ${C.sapphire}; }

/* ── JOB REFERENCE BANNER ── */
.job-ref {
  flex-shrink: 0;
  padding: 11px 32px;
  background: ${C.mantle};
  border-bottom: 1px solid ${C.surface0};
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.job-ref-left {
  display: flex;
  align-items: center;
  gap: 10px;
}
.job-ref-badge {
  display: inline-flex;
  align-items: center;
  padding: 3px 14px 3px 10px;
  background: ${C.blue};
  color: ${C.crust};
  font-family: 'Rajdhani', sans-serif;
  font-size: 8px;
  font-weight: 700;
  letter-spacing: 2px;
  text-transform: uppercase;
  clip-path: polygon(0 0, calc(100% - 7px) 0, 100% 50%, calc(100% - 7px) 100%, 0 100%);
}
.job-ref-title {
  font-family: 'Rajdhani', sans-serif;
  font-size: 13px;
  font-weight: 700;
  letter-spacing: 0.5px;
  color: ${C.text};
  text-shadow: 0 0 10px ${C.blue}44;
}
.job-ref-company {
  font-size: 9px;
  color: ${C.sapphire};
  font-weight: 600;
  margin-top: 1px;
}
.job-ref-date {
  font-family: 'Rajdhani', sans-serif;
  font-size: 8px;
  font-weight: 600;
  color: ${C.overlay1};
  letter-spacing: 1px;
  text-transform: uppercase;
  border-left: 2px solid ${C.surface1};
  padding-left: 10px;
}

/* ── LETTER BODY ── */
.letter-body {
  flex: 1;
  padding: 28px 40px 24px;
  overflow: hidden;
}
.letter-body p {
  color: ${C.subtext1};
  font-size: 10.5px;
  line-height: 1.65;
  margin-bottom: 0;
}
.para-gap { height: 10px; }

/* ── SIGNATURE ── */
.signature {
  flex-shrink: 0;
  padding: 14px 40px 20px;
  border-top: 1px solid ${C.surface0};
}
.sig-name {
  font-family: 'Cinzel', serif;
  font-size: 13px;
  font-weight: 700;
  color: ${C.text};
  letter-spacing: 0.8px;
  text-shadow: 0 0 14px ${C.blue}44;
  margin-bottom: 2px;
}
.sig-contact {
  font-size: 8.5px;
  color: ${C.subtext0};
}

/* ── FOOTER ── */
.ltr-footer {
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 6px 24px;
  background: ${C.crust};
  border-top: 1px solid ${C.surface0};
  font-family: 'Rajdhani', sans-serif;
  font-size: 7.5px;
  font-weight: 600;
  letter-spacing: 1px;
  color: ${C.subtext0};
}
.footer-icon { color: ${C.blue}; }
.footer-sep  { color: ${C.surface2}; font-size: 6px; }
.footer-link { color: ${C.blue}; text-decoration: none; letter-spacing: 0; font-weight: 500; }
</style>
</head>
<body>

<header>
  <div class="ltr-bracket"></div>
  <div class="ltr-name">
    ${p.personal.name.split(" ").slice(0, -1).join(" ")} <em>${p.personal.name.split(" ").slice(-1)[0]}</em>
  </div>
  <div class="ltr-contacts">
    <span><span class="ic">✉</span>${p.personal.email}</span>
    <span><span class="ic">☏</span>${p.personal.phone}</span>
    <span><span class="ic">◈</span>${p.personal.location}</span>
    ${p.personal.github ? `<span><span class="ic">⌘</span>${p.personal.github}</span>` : ""}
    ${p.personal.website ? `<span><span class="ic">⌂</span>${p.personal.website}</span>` : ""}
  </div>
</header>

<div class="job-ref">
  <div class="job-ref-left">
    <span class="job-ref-badge">▸ Application</span>
    <div>
      <div class="job-ref-title">${jobTitle}</div>
      <div class="job-ref-company">${company}</div>
    </div>
  </div>
  <div class="job-ref-date">${date}</div>
</div>

<div class="letter-body">
  ${bodyLines}
</div>

<div class="signature">
  <div class="sig-name">${p.personal.name}</div>
  <div class="sig-contact">${p.personal.email} &nbsp;·&nbsp; ${p.personal.phone}</div>
</div>

${footerHtml}
</body>
</html>`;
}
