import {
  existsSync,
  readdirSync,
  mkdirSync,
  writeFileSync,
  unlinkSync,
} from "fs";
import path from "path";
import chalk from "chalk";
import { loadProfile, type Profile } from "./profile";

const ASSETS_DIR = "assets";
const OUT_DIR = "data";
const OUT_FILE = `${OUT_DIR}/cv.pdf`;
const TMP_HTML = `${OUT_DIR}/_cv_tmp.html`;

// Catppuccin Mocha
const C = {
  base: "#1e1e2e",
  mantle: "#181825",
  crust: "#11111b",
  surface0: "#313244",
  surface1: "#45475a",
  surface2: "#585b70",
  overlay1: "#7f849c",
  subtext0: "#a6adc8",
  subtext1: "#bac2de",
  text: "#cdd6f4",
  lavender: "#b4befe",
  blue: "#89b4fa",
  sapphire: "#74c7ec",
  sky: "#89dceb",
  teal: "#94e2d5",
  green: "#a6e3a1",
  yellow: "#f9e2af",
  peach: "#fab387",
  mauve: "#cba6f7",
  pink: "#f5c2e7",
};

function findPhoto(): string | null {
  if (!existsSync(ASSETS_DIR)) return null;

  const file = readdirSync(ASSETS_DIR).find((f) =>
    /^photo\.(jpg|jpeg|png|webp)$/i.test(f),
  );

  return file ? path.join(ASSETS_DIR, file) : null;
}

async function photoToDataUrl(filePath: string): Promise<string> {
  const buf = await Bun.file(filePath).arrayBuffer();

  const ext = path.extname(filePath).slice(1).toLowerCase();
  const mime = ext === "jpg" ? "jpeg" : ext;

  return `data:image/${mime};base64,${Buffer.from(buf).toString("base64")}`;
}

function tag(label: string, muted = false): string {
  const bg = muted ? C.surface0 : C.surface1;
  const color = muted ? C.overlay1 : C.blue;
  const border = muted ? C.surface1 : C.surface2;

  return `
    <span style="
      display:inline-block;
      background:${bg};
      color:${color};
      border:1px solid ${border};
      border-radius:4px;
      padding:2px 7px;
      font-size:9px;
      margin:2px 2px 2px 0;
      font-family:'Rajdhani',sans-serif;
      font-weight:600;
      letter-spacing:0.3px;
    ">
      ${label}
    </span>
  `;
}

function renderSkillGroups(skills: Record<string, string[]>): string {
  return Object.entries(skills)
    .map(([category, values]) => {
      if (!Array.isArray(values)) return "";

      const title = category
        .replace(/_/g, " ")
        .replace(/\b\w/g, (c) => c.toUpperCase());

      return `
        <div style="margin-bottom:12px">
          <div style="
            font-size:8px;
            color:${C.overlay1};
            margin-bottom:4px;
            font-family:'Rajdhani',sans-serif;
            letter-spacing:1.5px;
            text-transform:uppercase;
          ">
            ${title}
          </div>

          <div>
            ${values.map((s) => tag(s)).join("")}
          </div>
        </div>
      `;
    })
    .join("");
}

function buildHtml(p: Profile, photoUrl: string | null): string {
  const attr = p.attribution;

  const attrHtml = attr?.enabled
    ? `
      <footer class="cv-footer">
        <span class="footer-icon">⚙</span>
        GENERATED BY JOBBOT
        <span class="footer-sep">◆</span>
        <a href="${attr.repo}" class="footer-link">
          ${attr.repo}
        </a>
      </footer>
    `
    : "";

  const r = p.recent_role;
  const prevExp = p.previous_experience;

  return `
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">

<link rel="preconnect" href="https://fonts.googleapis.com">

<link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@600;700;900&family=Rajdhani:wght@500;600;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">

<style>

@page {
  margin: 0;
  size: A4;
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html,
body {
  width: 210mm;
  height: 297mm;
}

body {
  background: ${C.base};
  color: ${C.text};
  font-family: 'Inter', system-ui, sans-serif;
  font-size: 10px;
  line-height: 1.5;
  display: flex;
  flex-direction: column;
}

/* ───────────────── HEADER ───────────────── */

header {
  position: relative;
  min-height: 120px;
  background: ${C.crust};
  border-bottom: 2px solid ${C.blue};
  overflow: hidden;
  flex-shrink: 0;
}

.hero-glow {
  position: absolute;
  top: -40px;
  left: -20px;
  width: 260px;
  height: 200px;
  background: radial-gradient(
    ellipse,
    ${C.blue}22 0%,
    transparent 70%
  );
  pointer-events: none;
}

.hero-photo {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  width: 45%;
}

.hero-photo img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  object-position: top center;
}

.hero-photo::after {
  content: '';
  position: absolute;
  inset: 0;

  background:
    linear-gradient(
      to right,
      ${C.crust} 0%,
      ${C.crust}dd 18%,
      ${C.crust}88 45%,
      transparent 85%
    ),

    linear-gradient(
      to bottom,
      ${C.crust}66 0%,
      transparent 35%
    );
}

.header-content {
  position: relative;
  z-index: 5;
  padding: 22px 24px 18px;
  max-width: 64%;
}

.header-content::before {
  content: '';
  position: absolute;
  top: 12px;
  left: 14px;
  width: 14px;
  height: 14px;
  border-top: 2px solid ${C.blue};
  border-left: 2px solid ${C.blue};
}

h1 {
  font-family: 'Cinzel', serif;
  font-size: 23px;
  font-weight: 900;
  line-height: 1.1;
  letter-spacing: 1.4px;
  color: ${C.text};
}

h1 em {
  color: ${C.blue};
  font-style: normal;
}

.role-badge {
  display: inline-flex;
  align-items: center;
  margin: 8px 0 10px;

  padding: 4px 10px;

  background: ${C.blue};
  color: ${C.crust};

  font-family: 'Rajdhani', sans-serif;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 1.8px;
  text-transform: uppercase;

  border-radius: 4px;
}

.contacts {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  font-size: 8.8px;
  color: ${C.subtext0};
}

.contacts span {
  display: flex;
  align-items: center;
  gap: 4px;
}

.contacts .ic {
  color: ${C.sapphire};
}

.summary-text {
  margin-top: 10px;

  max-width: 460px;

  padding-left: 10px;
  border-left: 2px solid ${C.surface2};

  color: ${C.subtext0};
  font-size: 9.2px;
  line-height: 1.55;
}

.core-stack {
  margin-top: 10px;

  display: flex;
  flex-wrap: wrap;
  gap: 5px;
}

/* ───────────────── LAYOUT ───────────────── */

.body {
  display: grid;
  grid-template-columns: 1fr 37%;
  flex: 1;
}

.main {
  padding: 16px 18px 16px 20px;
  border-right: 1px solid ${C.surface0};
}

.side {
  padding: 16px;
  background: ${C.mantle};
}

/* ───────────────── SECTIONS ───────────────── */

section {
  margin-bottom: 15px;
}

h2 {
  display: flex;
  align-items: center;
  gap: 7px;

  margin-bottom: 9px;
  padding-bottom: 4px;

  border-bottom: 1px solid ${C.surface0};

  font-family: 'Rajdhani', sans-serif;
  font-size: 9.5px;
  font-weight: 700;
  letter-spacing: 3px;
  text-transform: uppercase;

  color: ${C.blue};
}

h2 .h2-diamond {
  width: 6px;
  height: 6px;
  background: currentColor;
  transform: rotate(45deg);
}

h2.mauve { color: ${C.mauve}; }
h2.teal { color: ${C.teal}; }
h2.lavender { color: ${C.lavender}; }

/* ───────────────── EXPERIENCE ───────────────── */

.exp-card {
  background: ${C.surface0};

  border: 1px solid ${C.surface1};
  border-left: 3px solid ${C.blue};

  padding: 10px 14px;
  margin-bottom: 10px;

  border-radius: 6px;
}

.exp-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 2px;
}

.exp-title {
  font-family: 'Rajdhani', sans-serif;
  font-size: 12px;
  font-weight: 700;
  text-transform: uppercase;
  color: ${C.text};
}

.exp-period {
  background: ${C.mauve};
  color: ${C.crust};

  padding: 2px 7px;
  border-radius: 4px;

  font-family: 'Rajdhani', sans-serif;
  font-size: 8.5px;
  font-weight: 700;
}

.exp-company {
  margin-bottom: 2px;

  color: ${C.sapphire};

  font-size: 9px;
  font-weight: 600;
}

.exp-reason {
  margin-bottom: 7px;

  color: ${C.overlay1};

  font-size: 8.2px;
  font-style: italic;
}

.exp-card ul {
  padding-left: 14px;
}

.exp-card li {
  margin-bottom: 3px;

  color: ${C.subtext1};
  font-size: 9px;
  line-height: 1.45;
}

.exp-card li::marker {
  color: ${C.teal};
}

.prev-entry {
  margin-bottom: 6px;

  padding: 5px 0 5px 10px;

  border-left: 2px solid ${C.surface1};

  color: ${C.subtext0};
  font-size: 8.8px;
  line-height: 1.45;
}

/* ───────────────── SIDEBAR ───────────────── */

.edu-entry {
  margin-bottom: 6px;

  padding: 6px 8px;

  background: ${C.surface0};
  border-left: 2px solid ${C.lavender};
  border-radius: 4px;

  color: ${C.subtext1};
  font-size: 8.8px;
  line-height: 1.4;
}

.lang-entry {
  padding: 4px 0;

  border-bottom: 1px solid ${C.surface0};

  color: ${C.subtext1};
  font-size: 9px;
}

.lang-entry:last-child {
  border-bottom: none;
}

/* ───────────────── FOOTER ───────────────── */

.cv-footer {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;

  padding: 8px 24px;

  background: ${C.crust};
  border-top: 1px solid ${C.surface0};

  color: ${C.subtext0};

  font-family: 'Rajdhani', sans-serif;
  font-size: 9px;
  font-weight: 600;
  letter-spacing: 1px;
}

.footer-icon {
  color: ${C.blue};
}

.footer-sep {
  color: ${C.surface2};
}

.footer-link {
  color: ${C.blue};
  text-decoration: none;
}

</style>
</head>

<body>

<header>

  <div class="hero-glow"></div>

  ${
    photoUrl
      ? `
        <div class="hero-photo">
          <img src="${photoUrl}" alt="">
        </div>
      `
      : ""
  }

  <div class="header-content">

    <h1>
      ${p.personal.name.split(" ").slice(0, -1).join(" ")}

      <em>
        ${p.personal.name.split(" ").slice(-1)[0]}
      </em>
    </h1>

    <div class="role-badge">
      ▸ Technical Generalist · IT Specialist · Game Industry
    </div>

    <div class="contacts">

      <span>
        <span class="ic">✉</span>
        ${p.personal.email}
      </span>

      <span>
        <span class="ic">☏</span>
        ${p.personal.phone}
      </span>

      <span>
        <span class="ic">◈</span>
        ${p.personal.location}
      </span>

      ${
        p.personal.github
          ? `
            <span>
              <span class="ic">⌘</span>
              ${p.personal.github}
            </span>
          `
          : ""
      }

      ${
        p.personal.website
          ? `
            <span>
              <span class="ic">⌂</span>
              ${p.personal.website}
            </span>
          `
          : ""
      }

    </div>

    ${
      p.personal.summary
        ? `
          <div class="summary-text">
            ${p.personal.summary}
          </div>
        `
        : ""
    }

    <div class="core-stack">
      ${["TypeScript", "React", "Linux", "DevOps", "Unity", "Python"]
        .map((s) => tag(s))
        .join("")}
    </div>

  </div>

</header>

<div class="body">

  <div class="main">

    <section>

      <h2>
        <span class="h2-diamond"></span>
        Experience
      </h2>

      <div class="exp-card">

        <div class="exp-header">

          <span class="exp-title">
            ${r.title}
          </span>

          <span class="exp-period">
            ${r.period}
          </span>

        </div>

        <div class="exp-company">
          ${r.company}
        </div>

        <div class="exp-reason">
          ${r.end_reason}
        </div>

        <ul>
          ${r.duties.map((d) => `<li>${d}</li>`).join("")}
        </ul>

      </div>

      ${prevExp
        .map(
          (e) => `
            <div class="prev-entry">
              <span style="
                color:${C.teal};
                font-weight:700;
                font-family:'Rajdhani',sans-serif;
                letter-spacing:1px;
              ">
                ▸
              </span>

              ${e.entry}
            </div>
          `,
        )
        .join("")}

    </section>

    <section>

      <h2 class="lavender">
        <span class="h2-diamond"></span>
        Education
      </h2>

      ${p.education
        .map(
          (e) => `
            <div class="edu-entry">
              ${e.entry}
            </div>
          `,
        )
        .join("")}

    </section>


    <section>

      <h2 class="mauve">
        <span class="h2-diamond"></span>
        Languages
      </h2>

      ${p.languages.list
        .map(
          (l) => `
            <div class="lang-entry">
              ${l}
            </div>
          `,
        )
        .join("")}

    </section>

    <section>

      <h2 class="teal">
        <span class="h2-diamond"></span>
        Interests
      </h2>

      <div>
        ${(p.hobbies ?? []).map((h) => tag(h, true)).join("")}
      </div>

    </section>

  </div>

  <div class="side">

    <section>

      <h2 class="teal">
        <span class="h2-diamond"></span>
        Skills
      </h2>

      ${renderSkillGroups(p.skills)}

    </section>


    <section>

      <h2>
        <span class="h2-diamond"></span>
        Environment
      </h2>

      <div style="
        display:flex;
        flex-direction:column;
        gap:5px;
      ">

    ${(p.dev_environment ?? [])
      .map(
        (e) => `
          <div style="
            font-size:8.5px;
            color:${C.subtext1};
            padding:5px 7px;
            background:${C.surface0};
            border-left:2px solid ${C.blue};
            line-height:1.35;
            border-radius:4px;
          ">
            ${e}
          </div>
        `,
      )
      .join("")}

      </div>

    </section>

  </div>

</div>

${attrHtml}

</body>
</html>
`;
}

async function htmlToPdf(htmlPath: string, outPath: string): Promise<void> {
  const absHtml = path.resolve(htmlPath);
  const absOut = path.resolve(outPath);

  const proc = Bun.spawn(
    [
      "chromium",
      "--headless",
      "--disable-gpu",
      "--no-sandbox",
      `--print-to-pdf=${absOut}`,
      "--print-to-pdf-no-header",
      "--no-pdf-header-footer",
      `file://${absHtml}`,
    ],
    {
      stdout: "pipe",
      stderr: "pipe",
    },
  );

  await new Response(proc.stdout).text();

  const err = await new Response(proc.stderr).text();

  const exitCode = await proc.exited;

  if (exitCode !== 0) {
    throw new Error(`chromium exited ${exitCode}: ${err.trim()}`);
  }
}

const profile = await loadProfile();

const photoPath = findPhoto();

const photoUrl = photoPath ? await photoToDataUrl(photoPath) : null;

if (photoPath) {
  console.log(chalk.dim(`Photo: ${photoPath}`));
}

const html = buildHtml(profile, photoUrl);

mkdirSync(OUT_DIR, { recursive: true });

writeFileSync(TMP_HTML, html);

process.stdout.write(chalk.dim("Generating CV PDF..."));

try {
  await htmlToPdf(TMP_HTML, OUT_FILE);

  console.log(chalk.green(" done"));
  console.log(chalk.bold(`Saved -> ${OUT_FILE}`));
} finally {
  if (existsSync(TMP_HTML)) {
    unlinkSync(TMP_HTML);
  }
}
